### ISSUE TITLE
How to remove snippets?

### ISSUE THREAD

**Issue by doufunao** [captainsafia/notebook-snippet-manager#1]
Hi,
as subject

Thank you!

**Comment by captainsafia** [comment]
Hello @doufunao! Thanks for opening this issue. It appears that I forgot to include the ability to remove snippets. I'll see if I can add this sometime soon.

**Comment by captainsafia** [comment]
Alright, @doufunao! I've added the ability to delete in the latest release. Let me know if it works alright for you.

**Comment by doufunao** [comment]
![image](https://cloud.githubusercontent.com/assets/4587510/23115438/d1c6eeaa-f77f-11e6-801b-3ffb53937b6a.png)

Hi captainsafia@
There is a delete button but it didn't work. I enable the checkbox and then click "Delete Snippet". Nothing happened...
